### ISSUE TITLE
migrate to appveyor

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/vcpkg.nuget#25]
Switching to appveyor seems likely to improve visibility of build failures which is huge for other contributors. This item tracks that migration, and the migration of the nuget auto-deploy.

@nefarius contributed an appveyor config file a while back that should get us started, capturing that here for now:

```
version: 1.5.{build}
image: Visual Studio 2017
install:
- git submodule -q update --init
before_build:
- nuget restore
platform: x86
configuration: Release
build:
  parallel: false
  project: Vcpkg-Nuget.sln
artifacts:
  - path: 'Release\*.nupkg'
```
